---
title: "Explore 1999-2016 Harvest Data"
output:
  html_document:
    df_print: paged
    fig_height: 8
    fig_width: 11
  pdf_document: default
---

```{r setup, include = FALSE, cache = FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
#knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
#knitr::opts_knit$set(root.dir = "C:/Dev/Projects/CafPlantGridPointSurvey/R/AggregateYieldAndBiomass_1999-2016")

library(tidyverse)
library(plotly)
library(sf)
library(tmap)
```

```{r}
source("../src/functions.R")
source("../src/cleaningFunctions.R")
```

```{r, include=FALSE}
setwd("../")
df <- get_clean1999_2016()
sf <- st_as_sf(df, coords = c("Longitude", "Latitude"), crs = 4326)
```

# Maps by year and crop
```{r, fig.width=11, fig.asp=1, out.width="100%"}
sf %>% 
  tm_shape() +
  tm_dots(size = 0.1, col = "Crop", palette = "Set1") +
  tm_facets(by="HarvestYear")
```


# Summary by year and crop
```{r}
p <- df %>% 
  filter(!is.na(GrainYieldDryPerArea)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = GrainYieldDryPerArea), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "yield (g / m2)")
ggplotly(p)
#p
```

```{r}
p <- df %>% 
  filter(!is.na(ResidueMassDryPerArea)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = ResidueMassDryPerArea), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "mean residue (g / m2)")
ggplotly(p)
#p
```

```{r}
p <- df %>% 
  filter(!is.na(ResidueMassDryPerArea) & !is.na(GrainYieldDryPerArea)) %>% 
  mutate(HarvestIndex = GrainYieldDryPerArea / (GrainYieldDryPerArea + ResidueMassDryPerArea)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = HarvestIndex), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "harvest index")
ggplotly(p)
#p
```

```{r}
p <- df %>% 
  filter(!is.na(GrainCarbon)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = GrainCarbon), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "grain carbon (%)")
ggplotly(p)
#p
```

```{r}
p <- df %>% 
  filter(!is.na(GrainNitrogen)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = GrainNitrogen), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "grain nitrogen (%)")
ggplotly(p)
#p
```

```{r}
p <- df %>% 
  filter(!is.na(ResidueCarbon)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = ResidueCarbon), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "residue carbon (%)")
ggplotly(p)
#p
```

```{r}
p <- df %>% 
  filter(!is.na(ResidueNitrogen)) %>% 
  ggplot(aes(x = as.factor(HarvestYear), y = ResidueNitrogen), na.rm = TRUE) +
  geom_boxplot() +  
    facet_wrap(~ Crop) +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "harvest year", y = "residue nitrogen (%)")
ggplotly(p)
#p
```